import type { Metadata } from "next";
import { M_PLUS_2 } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Footer } from "./footer";

const font = M_PLUS_2({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={cn("antialiased", font.className)}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
